# Generated by Django 2.2.7 on 2019-12-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='twitteruser',
            new_name='twitter_user',
        ),
    ]
